# Welcome to Jekyll!
#
# Site settings
#  encoding: ISO-8859-1

# from blog made locally
title: Albrecht Weinert's blog
email: gitBlog@a-weinert.de
description: >- # this means to ignore newlines until "baseurl:"
  Albrecht Weinert, blog on GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: a-weinert

permalink: /posts/:year/:month/:title.html

# Build settings
markdown: kramdown
# theme: minima

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag   # added 08.04.2019
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Albrecht Weinert"
      lang: en
      copyrightYear: 2019
      excerpt_separator: <!--more-->
      commentsURL: "https://github.com/a-weinert/a-weinert.github.io/issues"
      commentsAPI: "https://api.github.com/repos/a-weinert/a-weinert.github.io/issues"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" #
    values:
      author: "Albrecht Weinert"
      lang: en
      copyrightYear: 2019
      
